"""
AnomalyAlert model — stores security anomaly alerts.
Generated by the AI/ML anomaly detection pipeline.
"""

import uuid
from datetime import datetime
from sqlalchemy import String, Float, Boolean, Text, DateTime, Index, func
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column
from app.core.database import Base


class AnomalyAlert(Base):
    """Security anomaly alert generated by the ML pipeline."""

    __tablename__ = "anomaly_alerts"
    __table_args__ = (
        Index("idx_anomaly_time", "created_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )
    user_did: Mapped[str] = mapped_column(
        String(100), nullable=False, index=True
    )
    risk_score: Mapped[float] = mapped_column(Float, nullable=False)
    anomaly_type: Mapped[str] = mapped_column(String(50), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    severity: Mapped[str] = mapped_column(
        String(20), server_default="medium", index=True
    )
    anomalous_features: Mapped[dict] = mapped_column(JSONB, server_default="[]")
    acknowledged: Mapped[bool] = mapped_column(Boolean, server_default="false")
    acknowledged_by: Mapped[str | None] = mapped_column(String(100), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now()
    )

    def __repr__(self) -> str:
        return f"<AnomalyAlert did={self.user_did} severity={self.severity}>"
